services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g  # heap 사이즈 지정
    ports:
      - "9200:9200"
    networks:
      - overtime_network
    platform: linux/amd64

    # Logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: logstash
    ports:
      - "5044:5044"   # logback logstash appender 포트
      - "9600:9600"   # logstash HTTP API
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - overtime_network
    platform: linux/amd64

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - overtime_network
    platform: linux/amd64

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data
    networks:
      - overtime_network
    restart: always
    platform: linux/amd64

  zipkin:
    image: openzipkin/zipkin
    container_name: owlexpress-zipkin
    networks:
      - overtime_network
    ports:
      - "9411:9411"
    restart: always  # 선택사항: 실패 시 자동 재시작

  prometheus:
    image: prom/prometheus
    container_name: owlexpress-prometheus
    networks:
      - overtime_network
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: owlexpress-grafana
    networks:
      - overtime_network
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: always

  eureka:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: eureka
    environment:
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
    depends_on:
      - postgres
      - redis
      - logstash
    ports:
      - "19080:19080"
    networks:
      - overtime_network

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    environment:
      - GATEWAY_SERVER_PORT=${GATEWAY_SERVER_PORT}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19081:19081"
    networks:
      - overtime_network

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth
    environment:
      - AUTH_SERVER_PORT=${AUTH_SERVER_PORT}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - AUTH_JWT_ACCESS_EXP=${AUTH_JWT_ACCESS_EXP}
      - AUTH_JWT_REFRESH_EXP=${AUTH_JWT_REFRESH_EXP}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19082:19082"
    networks:
      - overtime_network

  user-service:
    build:
      context: ./user
      dockerfile: Dockerfile
    container_name: user
    environment:
      - USER_SERVER_PORT=${USER_SERVER_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19083:19083"
    networks:
      - overtime_network

  ai-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai
    environment:
      - AI_SERVER_PORT=${AI_SERVER_PORT}
      - AI_URL=${AI_URL}
      - AI_KEY=${AI_KEY}
      - AI_HUB_REQUEST_BASE=${AI_HUB_REQUEST_BASE}
      - AI_HUB_REQUEST_FORMAT=${AI_HUB_REQUEST_FORMAT}
      - AI_COMPANY_REQUEST_BASE=${AI_COMPANY_REQUEST_BASE}
      - AI_COMPANY_REQUEST_FORMAT=${AI_COMPANY_REQUEST_FORMAT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19084:19084"
    networks:
      - overtime_network

  alarm-service:
    build:
      context: ./alarm
      dockerfile: Dockerfile
    container_name: alarm
    environment:
      - ALARM_SERVER_PORT=${ALARM_SERVER_PORT}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - SLACK_TOKEN=${SLACK_TOKEN}
      - SLACK_FALLBACK_MESSAGE=${SLACK_FALLBACK_MESSAGE}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19085:19085"
    networks:
      - overtime_network

  product-service:
    build:
      context: ./product
      dockerfile: Dockerfile
    container_name: product
    environment:
      - PRODUCT_SERVER_PORT=${PRODUCT_SERVER_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19086:19086"
    networks:
      - overtime_network

  producer-service:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    environment:
      - PRODUCER_SERVER_PORT=${PRODUCER_SERVER_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19087:19087"
    networks:
      - overtime_network

  hub-service:
    build:
      context: ./hub
      dockerfile: Dockerfile
    container_name: hub
    environment:
      - HUB_SERVER_PORT=${HUB_SERVER_PORT}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19088:19088"
    networks:
      - overtime_network

  consumer-service:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: consumer
    environment:
      - CONSUMER_SERVER_PORT=${CONSUMER_SERVER_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19089:19089"
    networks:
      - overtime_network

  order-service:
    build:
      context: ./order
      dockerfile: Dockerfile
    container_name: order
    environment:
      - ORDER_SERVER_PORT=${ORDER_SERVER_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19090:19090"
    networks:
      - overtime_network

  payment-service:
    build:
      context: ./payment
      dockerfile: Dockerfile
    container_name: payment
    environment:
      - PAYMENT_SERVER_PORT=${PAYMENT_SERVER_PORT}
      - TOSS_CLIENT_KEY=${TOSS_CLIENT_KEY}
      - TOSS_SECRET_KEY=${TOSS_SECRET_KEY}
      - TOSS_AUTH_KEY=${TOSS_AUTH_KEY}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19091:19091"
    networks:
      - overtime_network

  delivery-service:
    build:
      context: ./delivery
      dockerfile: Dockerfile
    container_name: delivery
    environment:
      - DELIVERY_SERVER_PORT=${DELIVERY_SERVER_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19092:19092"
    networks:
      - overtime_network

  cart-service:
    build:
      context: ./cart
      dockerfile: Dockerfile
    container_name: cart
    environment:
      - CART_SERVER_PORT=${CART_SERVER_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19093:19093"
    networks:
      - overtime_network

  delivery-manager-service:
    build:
      context: ./deliveryManager
      dockerfile: Dockerfile
    container_name: delivery-manager
    environment:
      - DELIVERY_MANAGER_SERVER_PORT=${DELIVERY_MANAGER_SERVER_PORT}
      - EUREKA_HOST=${EUREKA_HOST}
      - EUREKA_PORT=${EUREKA_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ZIPKIN_HOST=${ZIPKIN_HOST}
      - ZIPKIN_PORT=${ZIPKIN_PORT}
      - ZIPKIN_SAMPLING_PROBABILITY=${ZIPKIN_SAMPLING_PROBABILITY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - LOGSTASH_HOST=${LOGSTASH_HOST}
    depends_on:
      - eureka
      - redis
      - logstash
    ports:
      - "19094:19094"
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  user-postgres:
    image: postgis/postgis:latest
    container_name: user-postgres
    platform: linux/amd64
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  ai-postgres:
    image: postgis/postgis:latest
    container_name: ai-postgres
    platform: linux/amd64
    ports:
      - "5429:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - ai_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  alarm-postgres:
    image: postgis/postgis:latest
    container_name: alarm-postgres
    platform: linux/amd64
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - alarm_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  product-postgres:
    image: postgis/postgis:latest
    container_name: product-postgres
    platform: linux/amd64
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - product_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  producer-postgres:
    image: postgis/postgis:latest
    container_name: producer-postgres
    platform: linux/amd64
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - producer_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network
  # PostgreSQL + PostGIS
  hub-postgres:
    image: postgis/postgis:latest
    container_name: hub-postgres
    platform: linux/amd64
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - hub_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  consumer-postgres:
    image: postgis/postgis:latest
    container_name: consumer-postgres
    platform: linux/amd64
    ports:
      - "5424:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - consumer_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  order-postgres:
    image: postgis/postgis:latest
    container_name: order-postgres
    platform: linux/amd64
    ports:
      - "5423:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network
  # PostgreSQL + PostGIS
  payment-postgres:
    image: postgis/postgis:latest
    container_name: payment-postgres
    platform: linux/amd64
    ports:
      - "5422:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  delivery-postgres:
    image: postgis/postgis:latest
    container_name: delivery-postgres
    platform: linux/amd64
    ports:
      - "5421:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - delivery_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  cart-postgres:
    image: postgis/postgis:latest
    container_name: cart-postgres
    platform: linux/amd64
    ports:
      - "5420:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

  # PostgreSQL + PostGIS
  delivery-manager-postgres:
    image: postgis/postgis:latest
    container_name: delivery-manager-postgres
    platform: linux/amd64
    ports:
      - "5419:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - delivery_manager_postgres_data:/var/lib/postgresql/data
    networks:
      - overtime_network

networks:
  overtime_network:
    driver: bridge

volumes:
  user_postgres_data:
  ai_postgres_data:
  alarm_postgres_data:
  product_postgres_data:
  producer_postgres_data:
  hub_postgres_data:
  consumer_postgres_data:
  order_postgres_data:
  payment_postgres_data:
  delivery_postgres_data:
  cart_postgres_data:
  delivery_manager_postgres_data:
  redis_data:
