services:
  postgres:
    image: postgis/postgis:latest  # PostgreSQL + PostGIS 포함된 이미지 사용
    networks:
      - overtime_network
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: overtime
    volumes:
      - postgres_data:/var/lib/postgresql/data  # 데이터 영구 저장

networks:
  overtime_network:
    driver: bridge

volumes:
  postgres_data:  # 볼륨 추가하여 데이터 유지