input {
  tcp {
    port => 5044
    codec => json_lines
  }
}
filter {
  json {
    source => "message"
    target => "parsed"
  }

  # parsed 안의 필드를 루트로 이동
  mutate {
    add_field => {
      "service" => "%{[parsed][service]}"
      "method" => "%{[parsed][method]}"
      "status" => "%{[parsed][status]}"
      "duration_ms" => "%{[parsed][duration_ms]}"
    }

    convert => {
      "duration_ms" => "integer"
    }
    lowercase => ["status", "service", "method"]
  }

  # timestamp가 파싱된 JSON 안에 있을 경우 날짜 매핑
  date {
    match => ["[parsed][timestamp]", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]  # ✅ 컨테이너 이름 기반 연결
    index => "owlexpress-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}