spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: hub-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6378}
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 1000
            read-timeout: 1000
            logger-level: basic
  datasource:
    hikari:
      maximum-pool-size: 32  # 기본은 10이라 너무 작음
      minimum-idle: 8
      idle-timeout: 600000
      connection-timeout: 3000
      max-lifetime: 1800000 # 30분

    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${HUB_POSTGRES_PORT:5425}/${POSTGRES_DB:overtime}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  #  kafka:
  #    bootstrap-servers: localhost:29092

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
      #        show_sql: true
      #        format_sql: true
      jdbc:
        batch_size: 100
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    open-in-view: false

  logging:
    logstash:
      host: ${LOGSTASH_HOST:localhost}
      port: ${LOGSTASH_PORT:5044}
    #  level:
    #    org.springframework.orm.jpa: DEBUG
    #    org.springframework.transaction.interceptor: TRACE
management:
  endpoints:
    jmx:
      exposure:
        include: prometheus
    web:
      exposure:
        include: refresh,health,beans,busrefresh,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        all: true
    enable:
      hibernate: true # 하이버네이트 메트릭 노출 허용
    tags:
      application: hub # 대시 보드 쿼리 쉽게
  #  zipkin:
  #    tracing:
  #      endpoint: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans"
  tracing:
    sampling:
      probability: ${ZIPKIN_SAMPLING_PROBABILITY:1.0}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${IP_ADDRESS}
    instance-id:
      ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
    metadataMap:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${server.port}"
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka

server:
  port: ${HUB_SERVER_PORT:19080}
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 200
    accept-count: 200
    max-connections: 3000
    connection-timeout: 5s

naver:
  client-id: ${NAVER_CLIENT_ID}
  client-secret: ${NAVER_CLIENT_SECRET}