spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  application:
    name: order-service
  datasource:
#    hikari:
#      maximum-pool-size: 1000
#      minimum-idle: 10
#      connection-timeout: 300
#      idle-timeout: 300
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${ORDER_POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 500
    accept-count: 100
    max-connections: 100
    connection-timeout: 5s
  port: ${ORDER_SERVER_PORT}

logging:
  logstash:
    host: ${LOGSTASH_HOST:localhost}
management:
  endpoints:
    jmx:
      exposure:
        include: prometheus
    web:
      exposure:
        include: refresh,health,beans,busrefresh,info,metrics,prometheus
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans"
  tracing:
    sampling:
      probability: ${ZIPKIN_SAMPLING_PROBABILITY:1.0}
  metrics:
    distribution:
      percentiles-histogram:
        all: true
eureka:
  instance:
    metadataMap:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${server.port}"
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka