server:
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 500
    accept-count: 1000
    max-connections: 10000
    connection-timeout: 5s
  port: ${ALARM_SERVER_PORT}
eureka:
  instance:
    metadataMap:
      prometheus.scrape: "true"
      prometheus.path: "/actuator/prometheus"
      prometheus.port: "${server.port}"
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  #  jackson:
  #    property-naming-strategy: SNAKE_CASE
  application:
    name: alarm-service
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  datasource:
    hikari:
      maximum-pool-size: 1000
      max-lifetime: 177000
      minimum-idle: 10
      connection-timeout: 30000

    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${ALARM_POSTGRES_PORT:5432}/${POSTGRES_DB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

api :
  connection-timeout: 3000
  read-timeout: 120000
  max-buffer-size-MB: 300

management:
  endpoints:
    jmx:
      exposure:
        include: prometheus
    web:
      exposure:
        include: refresh,health,beans,busrefresh,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        all: true
  zipkin:
    tracing:
      endpoint: "http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans"
  tracing:
    sampling:
      probability: ${ZIPKIN_SAMPLING_PROBABILITY:1.0}

slack :
  webhook :
    url: ${SLACK_WEBHOOK_URL}
  token : ${SLACK_TOKEN}

logging:
  logstash:
    host: ${LOGSTASH_HOST:localhost}
    port: ${LOGSTASH_PORT:5044}
massage :
  fallback : ${SLACK_FALLBACK_MESSAGE}